using System;
using UnityEngine;

namespace Projects.Scripts.Puzzle
{
    /// <summary>
    /// パズルピースの形状を定義するScriptableObject。
    /// Inspectorから形状を設定できる。
    /// </summary>
    [CreateAssetMenu(fileName = "NewPuzzlePieceShape", menuName = "Puzzle/Piece Shape")]
    public class PuzzlePieceShape : ScriptableObject
    {
        [Tooltip("形状の幅")]
        [SerializeField] private int width = 3;

        [Tooltip("形状の高さ")]
        [SerializeField] private int height = 3;

        [Tooltip("セルの占有状態（左下起点、行優先で width*height の要素数）")]
        [SerializeField] private bool[] cells;

        [Header("Dish Visual")]
        [Tooltip("食器のスプライト（未設定の場合は形状から自動生成されます）")]
        [SerializeField] private Sprite dishSprite;

        [Tooltip("食器スプライトの色調整")]
        [SerializeField] private Color dishColor = Color.white;

        private Sprite _autoGeneratedSprite;

        public int Width => width;
        public int Height => height;
        public Sprite DishSprite => dishSprite;
        public Color DishColor => dishColor;

        /// <summary>
        /// 設定されたスプライト、または設定されていない場合は自動生成したスプライトを返す
        /// </summary>
        public Sprite GetEffectiveSprite()
        {
            if (dishSprite != null) return dishSprite;
            if (_autoGeneratedSprite != null) return _autoGeneratedSprite;

            const int ppu = 16;
            var texWidth = width * ppu;
            var texHeight = height * ppu;

            var tex = new Texture2D(texWidth, texHeight, TextureFormat.RGBA32, false)
            {
                filterMode = FilterMode.Point // ドット絵用
            };

            var pixels = new Color[texWidth * texHeight];
            for (var i = 0; i < pixels.Length; i++) pixels[i] = Color.clear;

            var filledCells = GetFilledCells();
            foreach (var cell in filledCells)
            {
                for (var y = 0; y < ppu; y++)
                {
                    for (var x = 0; x < ppu; x++)
                    {
                        var px = cell.x * ppu + x;
                        var py = cell.y * ppu + y;
                        pixels[py * texWidth + px] = Color.white;
                    }
                }
            }

            tex.SetPixels(pixels);
            tex.Apply();

            _autoGeneratedSprite = Sprite.Create(tex, new Rect(0, 0, texWidth, texHeight), new Vector2(0.5f, 0.5f), ppu);
            return _autoGeneratedSprite;
        }

        /// <summary>
        /// 自動生成スプライトのキャッシュをクリアする
        /// </summary>
        public void ClearAutoSprite()
        {
            if (_autoGeneratedSprite != null)
            {
                DestroyImmediate(_autoGeneratedSprite.texture);
                DestroyImmediate(_autoGeneratedSprite);
                _autoGeneratedSprite = null;
            }
        }

        /// <summary>
        /// 指定座標のセルが埋まっているかどうかを返す。
        /// ローカル座標 (0,0) が左下。
        /// </summary>
        public bool GetCell(int x, int y)
        {
            if (x < 0 || x >= width || y < 0 || y >= height) return false;
            var index = y * width + x;
            if (index < 0 || index >= cells.Length) return false;
            return cells[index];
        }

        /// <summary>
        /// 形状に含まれるすべてのセルのローカル座標を返す。
        /// </summary>
        public Vector2Int[] GetFilledCells()
        {
            var count = 0;
            for (var i = 0; i < cells.Length; i++)
            {
                if (cells[i]) count++;
            }

            var result = new Vector2Int[count];
            var idx = 0;
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    if (GetCell(x, y))
                    {
                        result[idx++] = new Vector2Int(x, y);
                    }
                }
            }
            return result;
        }

        private void OnValidate()
        {
            if (width < 1) width = 1;
            if (height < 1) height = 1;

            var requiredLength = width * height;
            if (cells == null || cells.Length != requiredLength)
            {
                Array.Resize(ref cells, requiredLength);
            }
            
            // プロパティが変更されたら自動生成スプライトを破棄して再生成を促す
            _autoGeneratedSprite = null;
        }
    }
}
