using System;
using System.Collections.Generic;
using UnityEngine;

namespace Projects.Scripts.Puzzle
{
    [CreateAssetMenu(fileName = "NewPuzzlePieceShape", menuName = "Puzzle/Piece Shape")]
    public class PuzzlePieceShape : ScriptableObject
    {
        [SerializeField] private int width = 3;
        [SerializeField] private int height = 3;
        [SerializeField] private bool[] cells;

        [Header("Dish Info")]
        [Tooltip("皿の種類名（例: 大皿、小皿、コップ）")]
        [SerializeField] private string dishTypeName;

        [Header("Dish Visual")]
        [SerializeField] private Sprite[] dishSprites;

        [Header("Refill Settings")]
        [SerializeField, Min(0.1f)] private float refillIntervalSeconds = 3f;

        private Sprite _autoGeneratedSprite;

        public int Width => width;
        public int Height => height;
        public string DishTypeName => dishTypeName;
        public IReadOnlyList<Sprite> DishSprites => dishSprites;
        public float RefillIntervalSeconds => refillIntervalSeconds;

        public Sprite GetEffectiveSprite()
        {
            var pooledSprite = GetFirstAssignedSpriteFromPool();
            if (pooledSprite != null) return pooledSprite;
            if (_autoGeneratedSprite != null) return _autoGeneratedSprite;

            const int ppu = 16;
            var texWidth = width * ppu;
            var texHeight = height * ppu;

            var tex = new Texture2D(texWidth, texHeight, TextureFormat.RGBA32, false)
            {
                filterMode = FilterMode.Point
            };

            var pixels = new Color[texWidth * texHeight];
            for (var i = 0; i < pixels.Length; i++) pixels[i] = Color.clear;

            var filledCells = GetFilledCells();
            foreach (var cell in filledCells)
            {
                for (var y = 0; y < ppu; y++)
                {
                    for (var x = 0; x < ppu; x++)
                    {
                        var px = cell.x * ppu + x;
                        var py = cell.y * ppu + y;
                        pixels[py * texWidth + px] = Color.white;
                    }
                }
            }

            tex.SetPixels(pixels);
            tex.Apply();

            _autoGeneratedSprite = Sprite.Create(tex, new Rect(0, 0, texWidth, texHeight), new Vector2(0.5f, 0.5f), ppu);
            return _autoGeneratedSprite;
        }

        public Sprite GetSpriteAt(int index)
        {
            if (dishSprites == null || index < 0 || index >= dishSprites.Length) return null;
            return dishSprites[index];
        }

        public int GetAssignedDishSpriteCount()
        {
            if (dishSprites == null) return 0;

            var count = 0;
            foreach (var sprite in dishSprites)
            {
                if (sprite != null) count++;
            }

            return count;
        }

        public void ClearAutoSprite()
        {
            if (_autoGeneratedSprite != null)
            {
                DestroyImmediate(_autoGeneratedSprite.texture);
                DestroyImmediate(_autoGeneratedSprite);
                _autoGeneratedSprite = null;
            }
        }

        public bool GetCell(int x, int y)
        {
            if (x < 0 || x >= width || y < 0 || y >= height) return false;
            var index = y * width + x;
            if (index < 0 || index >= cells.Length) return false;
            return cells[index];
        }

        public Vector2Int[] GetFilledCells()
        {
            var count = 0;
            for (var i = 0; i < cells.Length; i++)
            {
                if (cells[i]) count++;
            }

            var result = new Vector2Int[count];
            var idx = 0;
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    if (GetCell(x, y))
                    {
                        result[idx++] = new Vector2Int(x, y);
                    }
                }
            }

            return result;
        }

        private Sprite GetFirstAssignedSpriteFromPool()
        {
            if (dishSprites == null) return null;

            foreach (var sprite in dishSprites)
            {
                if (sprite != null) return sprite;
            }

            return null;
        }

        private void OnValidate()
        {
            if (width < 1) width = 1;
            if (height < 1) height = 1;
            refillIntervalSeconds = Mathf.Max(0.1f, refillIntervalSeconds);

            var requiredLength = width * height;
            if (cells == null || cells.Length != requiredLength)
            {
                Array.Resize(ref cells, requiredLength);
            }

            _autoGeneratedSprite = null;
        }
    }
}
